# Generated by Django 5.2.6 on 2025-10-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_approved_at_depositrequest_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
