# Generated by Django 5.2.6 on 2025-10-02 22:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded')], default='holding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.depositrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
