# Generated by Django 5.2.6 on 2025-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
