# Generated by Django 5.2.6 on 2025-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_depositrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
