# Generated by Django 5.2.6 on 2025-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_depositrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
