# Generated by Django 5.2.6 on 2025-10-08 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_withdrawalrequest_wallet_and_more'),
        ('wallet', '0011_delete_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='confirmed_by_user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='description',
            field=models.CharField(blank=True, default='Cash withdrawal via agent', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
