# Generated by Django 5.2.6 on 2025-10-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
