# Generated by Django 5.2.6 on 2025-10-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_delete_activitylog'),
        ('wallet', '0011_delete_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_request', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='wallet.transaction'),
        ),
    ]
