# Generated by Django 5.2.6 on 2025-10-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='account_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
