# Generated by Django 5.2.6 on 2025-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentapplication_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
