# Generated by Django 5.2.6 on 2025-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentapplication_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='reference',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
