# Generated by Django 5.2.6 on 2025-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentapplication_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
