# Generated by Django 5.2.6 on 2025-09-29 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginactivity_session_key_alter_loginactivity_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginactivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='session_key',
            field=models.CharField(db_index=True, default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
