# Generated by Django 5.2.6 on 2025-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_account_name_profile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
