# Generated by Django 5.2.6 on 2025-10-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
