# Generated by Django 5.2.6 on 2025-10-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appeal_status',
            field=models.CharField(choices=[('none', 'No Appeal'), ('pending', 'Pending Review'), ('resolved', 'Resolved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_appeal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
