# Generated by Django 5.2.6 on 2025-10-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_appeal_status_profile_suspension_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agent_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
