# Generated by Django 5.2.6 on 2025-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee_low', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('transaction_fee_high', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('split_platform', models.PositiveIntegerField(default=60)),
                ('split_agent', models.PositiveIntegerField(default=40)),
                ('escrow_expiry_minutes', models.PositiveIntegerField(default=15)),
                ('min_transaction', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('max_transaction', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
