# Generated by Django 5.2.6 on 2025-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='agent_auto_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deposit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='fraud_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='homepage_banner_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='kyc_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='log_user_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_daily_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_daily_transactions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_email',
            field=models.EmailField(default='support@cashly.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_phone',
            field=models.CharField(default='+2340000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='withdrawal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='min_transaction',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='split_agent',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='split_platform',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
    ]
