# Generated by Django 5.2.6 on 2025-09-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_paymentrequest_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paystack_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paystack_transfer_code',
        ),
    ]
