# Generated by Django 5.2.6 on 2025-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
