# Generated by Django 5.2.6 on 2025-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_locked_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
