# Generated by Django 5.2.6 on 2025-10-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_agent_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='agent_commission',
        ),
    ]
