# Generated by Django 5.2.6 on 2025-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_transaction_agent_commission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_created_fb97c1_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_flagged',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
