# Generated by Django 5.2.6 on 2025-10-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_withdrawalrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
