# Generated by Django 5.2.6 on 2025-10-25 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_dispute_disputemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disputemessage',
            options={},
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='subject',
            new_name='issue_type',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='description',
        ),
        migrations.AddField(
            model_name='dispute',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='initiator_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispute',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction'),
        ),
    ]
