# Generated by Django 5.2.6 on 2025-10-27 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_dispute_options_alter_disputemessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputemessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='wallet.disputemessage'),
        ),
        migrations.AlterField(
            model_name='disputemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dispute_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
