# Generated by Django 5.2.6 on 2025-10-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_disputemessage_options_disputemessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputemessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Dispute Message', 'verbose_name_plural': 'Dispute Messages'},
        ),
    ]
